# Generated by Django 5.1.1 on 2024-09-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content", models.TextField()),
                ("cover_image_url", models.CharField(max_length=500)),
            ],
        ),
    ]
